### ISSUE TITLE
Resolve symbolic links

### ISSUE THREAD

**Issue by jbabyhacker** [tilpner/includedir#15]
Any interesting in accepting a PR that resolves symbolic links?

**Comment by tilpner** [comment]
*I'm not entirely sure what you mean, I'll assume you mean build-time symlink awareness to avoid including duplicated data. Correct me if I got it wrong.*

Yes, that seems sensible, but somewhat tricky to implement. You would have to detect and fully resolve all symlinks, and then share the `&'static [u8]` created via `include_bytes!` between each aliasing key.

The naive way would be to generate a bunch of statics, one for each real file, and then reference those while building the map.
But when you do that, you run into filenames that are not easily mapped to identifiers for those statics (remember filenames can include e.g. newlines), so you'll need some robust escaping.

I would prefer to avoid encoding the entire name with e.g. base64, because that would produce huge and unreadable generated files. I'm also not sure what the maximum identifier length is.


Although... I just tried to `include_bytes!` a 100MB random blob three times (normally, copied to a new file, and via a symlink), and the resulting binary was 101MB large in debug mode. I'm not sure how that works (rustc/linker?), or if we want to rely on such undocumented behavior. If that is acceptable, no changes would be needed?
